In [1]:
# First, make sure you have the necessary libraries
# !pip install pandas pyarrow

import pandas as pd

In [4]:
# Load the dataset from the local file
# Or directly from Hugging Face after downloading
# Correct relative path for your project
file_path = "../raw_data/data.parquet"
df = pd.read_parquet(file_path, engine="fastparquet")

# Explore the data
print(f"Dataset loaded with {len(df)} rows.")
print("Sample of the data:")
display(df.head(50))

Dataset loaded with 501887 rows.
Sample of the data:

,fdc_id,food_item,data_type,ingredients,serving_description,serving_amount,serving_unit,serving_gram_weight,Caffeine,"Calcium, Ca",...,Energy,"Fatty acids, total saturated","Fatty acids, total trans","Fiber, total dietary","Iron, Fe","Potassium, K",Protein,"Sodium, Na",Total lipid (fat),Vitamin D (D2 + D3)
0,1104647,"Garlic, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,NaN,...,597.00,NaN,NaN,2.7,NaN,NaN,6.62,NaN,0.38,NaN
1,1104705,"Flour, soy, defatted",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,338.0,...,366.00,NaN,NaN,NaN,7.34,2480.0,51.10,2.0,3.33,NaN
2,1104766,"Flour, soy, full-fat",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,258.0,...,1890.00,NaN,NaN,NaN,9.51,1860.0,38.60,2.0,20.70,NaN
3,1104812,"Flour, rice, brown",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,10.0,...,365.25,NaN,NaN,NaN,1.50,265.0,7.19,1.0,3.85,NaN
4,1104867,"Flour, rice, glutinous",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,10.0,...,1500.00,NaN,NaN,NaN,0.34,80.0,6.69,6.0,1.16,NaN
5,1104913,"Flour, pastry, unenriched, unbleached",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,17.0,...,1500.00,NaN,NaN,NaN,0.87,142.0,8.75,1.0,1.64,NaN
6,1104962,"Onions, white, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,21.0,...,35.00,NaN,NaN,1.2,0.15,141.0,0.89,2.0,0.13,NaN
7,1105430,"Apples, red delicious, with skin, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,5.0,...,258.00,NaN,NaN,2.0,0.00,95.0,0.19,0.0,0.21,NaN
8,1105547,"Apples, honeycrisp, with skin, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,4.0,...,60.00,NaN,NaN,1.7,0.00,98.0,0.10,0.0,0.10,NaN
9,1105664,"Apples, granny smith, with skin, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,5.0,...,59.00,NaN,NaN,2.5,0.07,116.0,0.27,0.0,0.14,NaN
10,1105781,"Apples, gala, with skin, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,7.0,...,61.00,NaN,NaN,2.1,0.06,106.0,0.13,0.0,0.15,NaN
11,1105897,"Apples, fuji, with skin, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,6.0,...,65.00,NaN,NaN,2.1,0.02,104.0,0.15,1.0,0.16,NaN
12,1163444,Honeysuckle White - fresh 97% ground white turkey,branded_food,"White Turkey, Natural Flavoring",Standard 100g serving,100.0,g,100.0,NaN,0.0,...,NaN,0.89,0.0,0.0,1.29,NaN,23.21,67.0,2.68,NaN
13,1163445,HONEYSUCKLE WHITE - honeysuckle whtie 85% grou...,branded_food,"Turkey, natural Flavoring.",Standard 100g serving,100.0,g,100.0,NaN,18.0,...,NaN,4.46,0.0,0.0,0.96,NaN,18.75,103.0,15.18,NaN
14,1163448,HONEYSUCKLE WHITE - turkey breast roast,branded_food,Turkey Breast,Standard 100g serving,100.0,g,100.0,NaN,18.0,...,107.00,0.00,0.0,0.0,1.29,NaN,25.00,49.0,0.45,NaN
15,1163449,HONEYSUCKLE WHITE - fresh 99% fat free turkey ...,branded_food,Turkey with up to 6% absorbed water,Standard 100g serving,100.0,g,100.0,NaN,18.0,...,107.00,0.00,0.0,0.0,1.29,NaN,25.00,80.0,0.89,NaN
16,1163452,HONEYSUCKLE WHITE - turkey thighs,branded_food,Turkey Thigh,Standard 100g serving,100.0,g,100.0,NaN,18.0,...,196.00,3.12,0.0,0.0,1.61,NaN,16.96,76.0,13.39,NaN
17,1163453,Honeysuckle White - hsw turkey breakfast sausa...,branded_food,"Turkey, water, sugar, contains less than 2%: n...",Standard 100g serving,100.0,g,100.0,NaN,0.0,...,162.00,2.70,0.0,0.0,1.95,NaN,16.22,689.0,9.46,NaN
18,1163454,Honeysuckle White - hsw maple turkey sausage,branded_food,"Turkey, water, sugar, contains less than 2%: n...",Standard 100g serving,100.0,g,100.0,NaN,0.0,...,176.00,2.70,0.0,0.0,1.95,NaN,16.22,635.0,9.46,NaN
19,1163455,HONEYSUCKLE WHITE - 85% ground turkey,branded_food,"Turkey, natural Flavoring.",Standard 100g serving,100.0,g,100.0,NaN,18.0,...,214.00,4.46,0.0,0.0,0.96,NaN,18.75,103.0,15.18,NaN
20,1163457,HONEYSUCKLE WHITE - fresh ground turkey 97%,branded_food,"Ground turkey,natural flavoring",Standard 100g serving,100.0,g,100.0,NaN,0.0,...,125.00,0.89,0.0,0.0,1.29,NaN,23.21,67.0,2.68,NaN
21,1163458,HONEYSUCKLE WHITE - lemon garlic turkey tender...,branded_food,"Solution Ingredients Turkey broth, canola oil,...",Standard 100g serving,100.0,g,100.0,NaN,71.0,...,107.00,0.00,0.0,0.0,0.96,NaN,18.75,420.0,3.57,NaN
22,1163462,HONEYSUCKLE WHITE - turkey v-wings portions,branded_food,"Turkey, contains up to 6% absorbed water.",Standard 100g serving,100.0,g,100.0,NaN,18.0,...,196.00,3.12,0.0,0.0,1.29,NaN,20.54,54.0,12.50,NaN
23,1163464,HONEYSUCKLE WHITE - frozen sweet italian turke...,branded_food,"Turkey, water, salt, corn syrup solids, spices...",Standard 100g serving,100.0,g,100.0,NaN,29.0,...,171.00,2.86,0.0,0.0,1.54,NaN,17.14,671.0,10.00,NaN
24,1163465,Honeysuckle White - hsw turkey wing portions,branded_food,Turkey Wings,Standard 100g serving,100.0,g,100.0,NaN,18.0,...,NaN,3.12,0.0,0.0,1.29,NaN,20.54,54.0,12.50,NaN
25,1163466,Honeysuckle White - hsw turkey neck pieces fam...,branded_food,Turkey Necks,Standard 100g serving,100.0,g,100.0,NaN,36.0,...,NaN,1.79,0.0,0.0,1.61,NaN,20.54,94.0,5.36,NaN
26,1163469,Honeysuckle White - hsw frozen young turkey 9....,branded_food,"Contains 9.5% Turkey Broth, Salt, Sugar, Natur...",Standard 100g serving,100.0,g,100.0,NaN,18.0,...,134.00,1.34,0.0,0.0,0.64,NaN,19.64,179.0,5.36,NaN
27,1163470,HONEYSUCKLE WHITE - italian style seasoned gro...,branded_food,"Turkey,seasoning (salt, spices, sugar, dextros...",Standard 100g serving,100.0,g,100.0,NaN,18.0,...,NaN,2.23,0.0,0.0,1.61,NaN,19.64,536.0,6.25,NaN
28,1163471,HONEYSUCKLE WHITE - 93/7 ground turkey,branded_food,"Turkey, natural Flavoring.",Standard 100g serving,100.0,g,100.0,NaN,0.0,...,NaN,2.23,0.0,0.0,1.61,NaN,19.64,76.0,7.14,NaN
29,1163473,Tuttorosso Green - 28oz. whole peeled plum tom...,branded_food,"Tomatoes, Tomato Juice, Contains Less Than 2% ...",Standard 100g serving,100.0,g,100.0,NaN,17.0,...,21.00,0.00,0.0,0.8,0.30,190.0,0.83,99.0,0.00,NaN
30,1163474,Tuttorosso Green - 28oz. nsa whole peeled plum...,branded_food,"Tomatoes, Tomato Juice, Less Than 2% of: Calci...",Standard 100g serving,100.0,g,100.0,NaN,17.0,...,21.00,0.00,0.0,0.8,0.30,190.0,0.83,17.0,0.00,NaN
31,1163475,Tuttorosso Green - 28oz. diced tomatoes in juice,branded_food,"Tomatoes, Tomato Juice, Less Than 2% Of: Salt,...",Standard 100g serving,100.0,g,100.0,NaN,17.0,...,21.00,0.00,0.0,0.8,0.30,190.0,0.83,149.0,0.00,NaN
32,1163476,Tuttorosso Green - tutturosso green 14.5oz. di...,branded_food,"Tomatoes, Tomato Juice, Less Than 2% Of: Salt,...",Standard 100g serving,100.0,g,100.0,NaN,0.0,...,21.00,0.00,0.0,0.8,0.00,190.0,0.83,149.0,0.00,NaN
33,1163477,Tuttorosso Green - tutturosso green 14.5oz. pe...,branded_food,"Tomatoes, Tomato Juice, Less Than 2% Of: Salt,...",Standard 100g serving,100.0,g,100.0,NaN,0.0,...,21.00,0.00,0.0,0.8,0.00,190.0,0.83,149.0,0.00,NaN
34,1163482,"Snack Pack - gel strawberry, 13 oz",branded_food,"Water, Sugar, Apple Juice from Concentrate (Wa...",Standard 100g serving,100.0,g,100.0,NaN,0.0,...,NaN,0.00,0.0,0.0,0.00,109.0,0.00,38.0,0.00,NaN
35,1163483,"Snack Pack - juicy gels strawberry and orange,...",branded_food,"STRAWBERRY INGREDIENTS: Water, Sugar, Apple Ju...",Standard 100g serving,100.0,g,100.0,NaN,0.0,...,NaN,0.00,0.0,0.0,0.00,109.0,0.00,38.0,0.00,NaN
36,1163484,PAM - extra virgin olive oil cooking spray - 6...,branded_food,"Extra Virgin Olive Oil*,Lecithin from Soybeans...",Standard 100g serving,100.0,g,100.0,NaN,0.0,...,NaN,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.00,NaN
37,1163485,Banquet - spaghetti and popcorn chicken dinner...,branded_food,"Spaghetti with Sauce: Cooked Spaghetti (Water,...",Standard 100g serving,100.0,g,100.0,NaN,30.0,...,152.00,1.01,0.0,2.0,0.91,230.0,5.56,212.0,5.05,NaN
38,1163487,ACT II - mini butter popcorn,branded_food,"Popping Corn, Palm Oil, Less than 2% of: Salt,...",Standard 100g serving,100.0,g,100.0,NaN,0.0,...,NaN,8.59,0.0,11.5,2.06,200.0,NaN,859.0,20.05,NaN
39,1163488,"Angela Mia - fully prepared pizza sauce, #10 c...",branded_food,"Tomato Puree (Water, Tomato Paste), Less than ...",Standard 100g serving,100.0,g,100.0,NaN,0.0,...,NaN,0.00,0.0,3.2,0.57,429.0,1.59,429.0,0.00,NaN
40,1163489,"Hunt's - hunts tomato sauce, pouch, 6/103 oz.,...",branded_food,"Tomato Puree (Water, Tomato Paste), Water, les...",Standard 100g serving,100.0,g,100.0,NaN,0.0,...,NaN,0.00,0.0,1.6,0.00,290.0,1.61,613.0,0.00,NaN
41,1163490,Hunt's - hunts organic diced tomatoes,branded_food,"Organic Diced Tomatoes, Organic Tomato Juice, ...",Standard 100g serving,100.0,g,100.0,NaN,0.0,...,NaN,0.00,0.0,1.5,0.00,215.0,0.77,154.0,0.00,NaN
42,1163491,"Hunt's - hunts organic tomato sauce, 15 oz",branded_food,"Organic Tomato Puree (Water, Organic Tomato Pa...",Standard 100g serving,100.0,g,100.0,NaN,0.0,...,NaN,0.00,0.0,3.2,0.00,290.0,1.61,613.0,0.00,NaN
43,1163492,"Hunt's - hunts organic tomato paste, 6 oz",branded_food,"Organic Tomato Paste, Citric Acid",Standard 100g serving,100.0,g,100.0,NaN,0.0,...,NaN,0.00,0.0,6.1,3.27,939.0,3.03,76.0,0.00,NaN
44,1163493,"Hunt's - hunts tomato puree, pouch, 6/105 oz.",branded_food,"Tomato Puree (Water, Tomato Paste), Citric Acid.",Standard 100g serving,100.0,g,100.0,NaN,0.0,...,NaN,0.00,0.0,3.2,0.57,540.0,3.17,40.0,0.00,NaN
45,1163494,"Hunt's - hunts tomato puree, #10 can, 6/107 oz...",branded_food,"Tomato Puree (Water, Tomato Paste), Citric Acid.",Standard 100g serving,100.0,g,100.0,NaN,0.0,...,NaN,0.00,0.0,3.2,0.57,540.0,3.17,40.0,0.00,NaN
46,1163496,"Hunt's - tomato puree, 29 oz, 29 oz",branded_food,"Tomato Puree (Water, Tomato Paste), less than ...",Standard 100g serving,100.0,g,100.0,NaN,0.0,...,NaN,0.00,0.0,3.2,0.58,452.0,1.61,145.0,0.00,NaN
47,1163497,"Hunt's - hunts tomato paste, 29 oz",branded_food,"Tomato Paste, Citric Acid",Standard 100g serving,100.0,g,100.0,NaN,0.0,...,NaN,0.00,0.0,6.1,3.27,939.0,3.03,76.0,0.00,NaN
48,1163498,"Hunt's - hunts no salt added tomato sauce, 8 oz",branded_food,"Tomato Puree (Water, Tomato Paste), Water, Les...",Standard 100g serving,100.0,g,100.0,NaN,0.0,...,NaN,0.00,0.0,1.6,0.00,274.0,1.61,32.0,0.00,NaN
49,1163499,"Angela Mia - petite diced tomatoes, #10 can, 6...",branded_food,"Vine-Ripened Tomatoes, Tomato Juice, Less than...",Standard 100g serving,100.0,g,100.0,NaN,33.0,...,NaN,0.00,0.0,0.8,0.00,248.0,0.83,256.0,0.00,NaN

In [8]:
df[df["data_type"] != "branded_food"]

,fdc_id,food_item,data_type,ingredients,serving_description,serving_amount,serving_unit,serving_gram_weight,Caffeine,"Calcium, Ca",...,Energy,"Fatty acids, total saturated","Fatty acids, total trans","Fiber, total dietary","Iron, Fe","Potassium, K",Protein,"Sodium, Na",Total lipid (fat),Vitamin D (D2 + D3)
0,1104647,"Garlic, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,NaN,...,597.00,NaN,NaN,2.7,NaN,NaN,6.620000,NaN,0.3800,NaN
1,1104705,"Flour, soy, defatted",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,338.000,...,366.00,NaN,NaN,NaN,7.34000,2480.00,51.100000,2.0000,3.3300,NaN
2,1104766,"Flour, soy, full-fat",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,258.000,...,1890.00,NaN,NaN,NaN,9.51000,1860.00,38.600000,2.0000,20.7000,NaN
3,1104812,"Flour, rice, brown",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,10.000,...,365.25,NaN,NaN,NaN,1.50000,265.00,7.190000,1.0000,3.8500,NaN
4,1104867,"Flour, rice, glutinous",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,10.000,...,1500.00,NaN,NaN,NaN,0.34000,80.00,6.690000,6.0000,1.1600,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
417330,2346410,"Raspberries, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,16.410,...,NaN,NaN,NaN,NaN,0.45010,155.80,1.008125,0.0000,0.1875,NaN
417331,2346411,"Blueberries, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,11.690,...,NaN,NaN,NaN,NaN,0.33980,85.64,0.703125,0.0000,0.3063,NaN
417332,2346412,"Grapes, red, seedless, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,10.170,...,NaN,NaN,NaN,NaN,0.16150,229.40,0.914375,6.9990,0.1638,NaN
417333,2346413,"Grapes, green, seedless, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,9.897,...,NaN,NaN,NaN,NaN,0.19910,218.10,0.898750,3.1710,0.2325,NaN
417334,2346414,"Applesauce, unsweetened, with added vitamin C",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,3.821,...,NaN,NaN,NaN,NaN,0.04475,107.70,0.273438,0.5038,0.1625,NaN

In [14]:
df_filtered = df[
    (df["data_type"] != "branded_food") &
    (df["ingredients"].str.lower() != "none")
]

df_filtered.head(50)

,fdc_id,food_item,data_type,ingredients,serving_description,serving_amount,serving_unit,serving_gram_weight,Caffeine,"Calcium, Ca",...,Energy,"Fatty acids, total saturated","Fatty acids, total trans","Fiber, total dietary","Iron, Fe","Potassium, K",Protein,"Sodium, Na",Total lipid (fat),Vitamin D (D2 + D3)
0,1104647,"Garlic, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,NaN,...,597.00,NaN,NaN,2.7000,NaN,NaN,6.620000,NaN,0.3800,NaN
1,1104705,"Flour, soy, defatted",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,338.000,...,366.00,NaN,NaN,NaN,7.3400,2480.00,51.100000,2.0000,3.3300,NaN
2,1104766,"Flour, soy, full-fat",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,258.000,...,1890.00,NaN,NaN,NaN,9.5100,1860.00,38.600000,2.0000,20.7000,NaN
3,1104812,"Flour, rice, brown",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,10.000,...,365.25,NaN,NaN,NaN,1.5000,265.00,7.190000,1.0000,3.8500,NaN
4,1104867,"Flour, rice, glutinous",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,10.000,...,1500.00,NaN,NaN,NaN,0.3400,80.00,6.690000,6.0000,1.1600,NaN
5,1104913,"Flour, pastry, unenriched, unbleached",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,17.000,...,1500.00,NaN,NaN,NaN,0.8700,142.00,8.750000,1.0000,1.6400,NaN
6,1104962,"Onions, white, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,21.000,...,35.00,NaN,NaN,1.2000,0.1500,141.00,0.890000,2.0000,0.1300,NaN
7,1105430,"Apples, red delicious, with skin, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,5.000,...,258.00,NaN,NaN,2.0000,0.0000,95.00,0.190000,0.0000,0.2100,NaN
8,1105547,"Apples, honeycrisp, with skin, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,4.000,...,60.00,NaN,NaN,1.7000,0.0000,98.00,0.100000,0.0000,0.1000,NaN
9,1105664,"Apples, granny smith, with skin, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,5.000,...,59.00,NaN,NaN,2.5000,0.0700,116.00,0.270000,0.0000,0.1400,NaN
10,1105781,"Apples, gala, with skin, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,7.000,...,61.00,NaN,NaN,2.1000,0.0600,106.00,0.130000,0.0000,0.1500,NaN
11,1105897,"Apples, fuji, with skin, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,6.000,...,65.00,NaN,NaN,2.1000,0.0200,104.00,0.150000,1.0000,0.1600,NaN
126736,2512371,"Flour, amaranth",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,135.200,...,NaN,NaN,NaN,7.2090,7.5600,395.80,13.209300,0.0000,6.2360,NaN
126737,2512372,"Flour, quinoa",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,37.560,...,NaN,NaN,NaN,6.2950,4.5280,550.90,11.922350,6.3210,6.6010,NaN
126738,2512373,"Flour, sorghum",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,11.410,...,NaN,NaN,NaN,6.0190,3.7210,335.10,8.272770,0.0000,3.5860,NaN
126739,2512374,"Flour, buckwheat",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,30.550,...,NaN,NaN,NaN,10.3500,3.8400,378.10,8.884920,0.0000,2.4840,NaN
126740,2512375,"Flour, rye",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,32.240,...,NaN,NaN,NaN,13.6800,2.5360,434.00,8.395200,0.0000,1.9080,NaN
126741,2512376,"Flour, barley",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,35.560,...,NaN,NaN,NaN,12.7900,3.3010,366.60,8.721680,20.3300,2.4500,NaN
126742,2512377,"Flour, cassava",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,74.550,...,NaN,NaN,NaN,4.8340,3.9880,197.60,0.918225,13.0800,0.4938,NaN
126743,2512378,"Buckwheat, whole grain",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,13.640,...,NaN,NaN,NaN,4.0460,2.4440,414.50,11.065340,0.0000,3.0390,NaN
126744,2512379,"Millet, whole grain",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,9.105,...,NaN,NaN,NaN,2.6190,2.5340,214.10,10.021770,0.0000,4.1940,NaN
126745,2512380,"Rice, brown, long grain, unenriched, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,8.058,...,NaN,NaN,NaN,3.0210,1.2420,250.10,7.253050,0.0000,3.3060,NaN
126746,2512381,"Rice, white, long grain, unenriched, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,4.460,...,NaN,NaN,NaN,0.1488,0.1405,82.26,7.038850,0.4625,1.0330,NaN
126747,2514743,"Beef, ground, 90% lean meat / 10% fat, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,7.135,...,NaN,5.051,0.484,NaN,2.1280,281.40,18.156250,61.6400,12.8500,NaN
126748,2514744,"Beef, ground, 80% lean meat / 20% fat, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,6.889,...,NaN,6.845,0.700,NaN,1.9650,273.30,17.531250,54.9400,19.4400,NaN
126749,2514745,"Pork, ground, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,5.857,...,NaN,6.283,0.066,NaN,0.7876,317.70,17.806250,53.6300,17.4900,NaN
126750,2514746,"Chicken, ground, with additives, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,5.819,...,NaN,1.559,0.021,NaN,0.5926,301.70,17.912500,62.9500,7.1610,NaN
126751,2514747,"Turkey, ground, 93% lean/ 7% fat, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,23.630,...,NaN,2.264,0.081,NaN,1.0870,246.30,17.343750,80.1800,9.5910,NaN
126752,2515373,"Nuts, brazilnuts, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,167.800,...,NaN,NaN,NaN,5.9840,2.4740,592.50,15.036840,0.0000,57.4300,NaN
126753,2515374,"Nuts, cashew nuts, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,41.950,...,NaN,NaN,NaN,4.1040,5.9880,638.30,17.442300,4.7590,38.8600,NaN
126754,2515375,"Nuts, hazelnuts or filberts, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,134.700,...,NaN,NaN,NaN,8.4100,3.4650,635.90,13.493800,0.0000,53.4900,NaN
126755,2515376,"Peanuts, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,49.130,...,NaN,NaN,NaN,8.0140,1.5540,635.60,23.205000,1.4930,43.2800,NaN
126756,2515377,"Flour, chestnut",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,55.810,...,NaN,0.689,NaN,8.7110,1.6210,1032.00,5.286750,0.0000,4.6360,NaN
126757,2515378,"Nuts, macadamia nuts, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,52.710,...,NaN,NaN,NaN,7.5630,1.8810,372.60,7.785700,0.0000,64.9300,NaN
126758,2515379,"Nuts, pistachio nuts, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,117.400,...,NaN,NaN,NaN,6.9690,3.4560,947.00,20.505700,0.0000,45.0200,NaN
126759,2515380,"Seeds, pumpkin seeds (pepitas), raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,37.380,...,NaN,NaN,NaN,5.0790,8.3630,691.20,29.907900,0.0000,40.0300,NaN
126760,2515381,"Seeds, sunflower seed, kernel, raw",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,115.600,...,NaN,NaN,NaN,7.2150,4.3700,656.80,18.873300,0.0000,48.4400,NaN
126761,2515382,"Flour, coconut",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,35.980,...,NaN,13.999,NaN,34.2400,8.0180,2088.00,16.138500,46.9400,15.2800,NaN
197114,2644281,"Beans, cannellini, dry",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,142.900,...,NaN,NaN,NaN,NaN,6.6730,1424.00,21.562500,0.0000,2.1990,NaN
197115,2644282,"Chickpeas, (garbanzo beans, bengal gram), dry",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,111.100,...,NaN,NaN,NaN,NaN,5.0940,1074.00,21.275000,8.7790,6.2740,NaN
197116,2644283,"Lentils, dry",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,61.850,...,NaN,NaN,NaN,NaN,7.1580,948.90,23.568750,0.0000,1.9250,NaN
197117,2644284,"Blackeye pea, dry",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,71.400,...,NaN,NaN,NaN,NaN,5.9300,1243.00,21.225000,3.4580,2.4190,NaN
197118,2644285,"Beans, black, canned, sodium added, drained an...",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,43.310,...,NaN,NaN,NaN,NaN,1.6880,253.10,6.912500,217.9000,1.2730,NaN
197119,2644286,"Beans, navy, canned, sodium added, drained and...",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,63.910,...,NaN,NaN,NaN,NaN,1.5990,183.70,6.568750,190.1000,1.3980,NaN
197120,2644287,"Beans, cannellini, canned, sodium added, drain...",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,69.190,...,NaN,NaN,NaN,NaN,1.4050,202.60,7.412500,164.0000,1.1690,NaN
197121,2644288,"Chickpeas (garbanzo beans, bengal gram), canne...",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,40.480,...,NaN,NaN,NaN,NaN,1.0420,136.80,7.018750,201.7000,3.0960,NaN
197122,2644289,"Beans, kidney, dark red, canned, sodium added,...",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,56.940,...,NaN,NaN,NaN,NaN,1.4390,226.90,7.800000,172.3000,1.2560,NaN
197123,2644290,"Beans, kidney, light red, canned, sodium added...",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,60.250,...,NaN,NaN,NaN,NaN,1.3050,209.40,7.306250,158.5000,1.2990,NaN
197124,2644291,"Peas, green, sweet, canned, sodium added, suga...",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,28.210,...,NaN,NaN,NaN,NaN,1.1390,109.20,4.734375,207.4000,1.1530,NaN
197125,2644292,"Beans, pinto, canned, sodium added, drained an...",foundation_food,None,Standard 100g serving,100.0,g,100.0,NaN,55.230,...,NaN,NaN,NaN,NaN,1.2840,209.60,6.693750,201.6000,1.2660,NaN

In [3]:
df['Energy'].isnull().sum()

np.int64(51860)

In [6]:
COLUMNS_TO_KEEP = [
    "food_item",
    "data_type",
    "Energy",
    "Total lipid (fat)",
    "Fatty acids, total saturated",
    "Carbohydrate, by difference",
    "Protein",
    "Fiber, total dietary"
]

In [7]:
df_clean = df[COLUMNS_TO_KEEP].copy()
df_clean.head(20)

len(df_clean)

501887

In [8]:
# Remove branded_food rows
df_clean = df_clean[df_clean["data_type"] != "branded_food"].reset_index(drop=True)

len(df_clean)

8028

In [9]:
# add column with energy in kcal calculated
df_clean["energy_kcal_calculated"] = (
    df_clean["Total lipid (fat)"] * 9 +
    df_clean["Carbohydrate, by difference"] * 4 +
    df_clean["Protein"] * 4
).round(1)

df_clean.head(50)

,food_item,data_type,Energy,Total lipid (fat),"Fatty acids, total saturated","Carbohydrate, by difference",Protein,"Fiber, total dietary",energy_kcal_calculated
0,"Garlic, raw",foundation_food,597.00,0.3800,NaN,28.200000,6.620000,2.7000,142.7
1,"Flour, soy, defatted",foundation_food,366.00,3.3300,NaN,32.900000,51.100000,NaN,366.0
2,"Flour, soy, full-fat",foundation_food,1890.00,20.7000,NaN,27.900000,38.600000,NaN,452.3
3,"Flour, rice, brown",foundation_food,365.25,3.8500,NaN,75.500000,7.190000,NaN,365.4
4,"Flour, rice, glutinous",foundation_food,1500.00,1.1600,NaN,80.100000,6.690000,NaN,357.6
5,"Flour, pastry, unenriched, unbleached",foundation_food,1500.00,1.6400,NaN,77.200000,8.750000,NaN,358.6
6,"Onions, white, raw",foundation_food,35.00,0.1300,NaN,7.680000,0.890000,1.2000,35.4
7,"Apples, red delicious, with skin, raw",foundation_food,258.00,0.2100,NaN,14.800000,0.190000,2.0000,61.8
8,"Apples, honeycrisp, with skin, raw",foundation_food,60.00,0.1000,NaN,14.700000,0.100000,1.7000,60.1
9,"Apples, granny smith, with skin, raw",foundation_food,59.00,0.1400,NaN,14.200000,0.270000,2.5000,59.1
10,"Apples, gala, with skin, raw",foundation_food,61.00,0.1500,NaN,14.800000,0.130000,2.1000,61.1
11,"Apples, fuji, with skin, raw",foundation_food,65.00,0.1600,NaN,15.700000,0.150000,2.1000,64.8
12,"Flour, amaranth",foundation_food,NaN,6.2360,NaN,68.778700,13.209300,7.2090,384.1
13,"Flour, quinoa",foundation_food,NaN,6.6010,NaN,69.524650,11.922350,6.2950,385.2
14,"Flour, sorghum",foundation_food,NaN,3.5860,NaN,77.391230,8.272770,6.0190,374.9
15,"Flour, buckwheat",foundation_food,NaN,2.4840,NaN,75.018080,8.884920,10.3500,358.0
16,"Flour, rye",foundation_food,NaN,1.9080,NaN,77.161800,8.395200,13.6800,359.4
17,"Flour, barley",foundation_food,NaN,2.4500,NaN,77.398320,8.721680,12.7900,366.5
18,"Flour, cassava",foundation_food,NaN,0.4938,NaN,87.312975,0.918225,4.8340,357.4
19,"Buckwheat, whole grain",foundation_food,NaN,3.0390,NaN,71.130660,11.065340,4.0460,356.1
20,"Millet, whole grain",foundation_food,NaN,4.1940,NaN,74.446230,10.021770,2.6190,375.6
21,"Rice, brown, long grain, unenriched, raw",foundation_food,NaN,3.3060,NaN,76.687950,7.253050,3.0210,365.5
22,"Rice, white, long grain, unenriched, raw",foundation_food,NaN,1.0330,NaN,80.313150,7.038850,0.1488,358.7
23,"Beef, ground, 90% lean meat / 10% fat, raw",foundation_food,NaN,12.8500,5.051,0.000000,18.156250,NaN,188.3
24,"Beef, ground, 80% lean meat / 20% fat, raw",foundation_food,NaN,19.4400,6.845,0.000000,17.531250,NaN,245.1
25,"Pork, ground, raw",foundation_food,NaN,17.4900,6.283,0.000000,17.806250,NaN,228.6
26,"Chicken, ground, with additives, raw",foundation_food,NaN,7.1610,1.559,0.000000,17.912500,NaN,136.1
27,"Turkey, ground, 93% lean/ 7% fat, raw",foundation_food,NaN,9.5910,2.264,0.000000,17.343750,NaN,155.7
28,"Nuts, brazilnuts, raw",foundation_food,NaN,57.4300,NaN,21.642160,15.036840,5.9840,663.6
29,"Nuts, cashew nuts, raw",foundation_food,NaN,38.8600,NaN,36.288700,17.442300,4.1040,564.7
30,"Nuts, hazelnuts or filberts, raw",foundation_food,NaN,53.4900,NaN,26.501200,13.493800,8.4100,641.4
31,"Peanuts, raw",foundation_food,NaN,43.2800,NaN,26.498000,23.205000,8.0140,588.3
32,"Flour, chestnut",foundation_food,NaN,4.6360,0.689,80.450250,5.286750,8.7110,384.7
33,"Nuts, macadamia nuts, raw",foundation_food,NaN,64.9300,NaN,24.094300,7.785700,7.5630,711.9
34,"Nuts, pistachio nuts, raw",foundation_food,NaN,45.0200,NaN,27.694300,20.505700,6.9690,598.0
35,"Seeds, pumpkin seeds (pepitas), raw",foundation_food,NaN,40.0300,NaN,18.675100,29.907900,5.0790,554.6
36,"Seeds, sunflower seed, kernel, raw",foundation_food,NaN,48.4400,NaN,24.500700,18.873300,7.2150,609.5
37,"Flour, coconut",foundation_food,NaN,15.2800,13.999,58.902500,16.138500,34.2400,437.7
38,"Beans, cannellini, dry",foundation_food,NaN,2.1990,NaN,59.795500,21.562500,NaN,345.2
39,"Chickpeas, (garbanzo beans, bengal gram), dry",foundation_food,NaN,6.2740,NaN,60.358000,21.275000,NaN,383.0
40,"Lentils, dry",foundation_food,NaN,1.9250,NaN,62.171250,23.568750,NaN,360.3
41,"Blackeye pea, dry",foundation_food,NaN,2.4190,NaN,61.836000,21.225000,NaN,354.0
42,"Beans, black, canned, sodium added, drained an...",foundation_food,NaN,1.2730,NaN,19.813500,6.912500,NaN,118.4
43,"Beans, navy, canned, sodium added, drained and...",foundation_food,NaN,1.3980,NaN,19.983250,6.568750,NaN,118.8
44,"Beans, cannellini, canned, sodium added, drain...",foundation_food,NaN,1.1690,NaN,18.818500,7.412500,NaN,115.4
45,"Chickpeas (garbanzo beans, bengal gram), canne...",foundation_food,NaN,3.0960,NaN,20.320250,7.018750,NaN,137.2
46,"Beans, kidney, dark red, canned, sodium added,...",foundation_food,NaN,1.2560,NaN,21.030000,7.800000,NaN,126.6
47,"Beans, kidney, light red, canned, sodium added...",foundation_food,NaN,1.2990,NaN,21.446750,7.306250,NaN,126.7
48,"Peas, green, sweet, canned, sodium added, suga...",foundation_food,NaN,1.1530,NaN,12.707625,4.734375,NaN,80.1
49,"Beans, pinto, canned, sodium added, drained an...",foundation_food,NaN,1.2660,NaN,19.600250,6.693750,NaN,116.6

In [ ]:
# replace NaN in sat fat column with 0 where likely 0
import numpy as np

df_clean["Fatty acids, total saturated"] = np.where(
    (df_clean["Total lipid (fat)"] < 3) &
    (df_clean["Fatty acids, total saturated"].isna()),
    0,
    df_clean["Fatty acids, total saturated"]
)

df_clean.head(50)

,food_item,data_type,Energy,Total lipid (fat),"Fatty acids, total saturated","Carbohydrate, by difference",Protein,"Fiber, total dietary",energy_kcal_calculated
0,"Garlic, raw",foundation_food,597.00,0.3800,0.000,28.200000,6.620000,2.7000,142.7
1,"Flour, soy, defatted",foundation_food,366.00,3.3300,NaN,32.900000,51.100000,NaN,366.0
2,"Flour, soy, full-fat",foundation_food,1890.00,20.7000,NaN,27.900000,38.600000,NaN,452.3
3,"Flour, rice, brown",foundation_food,365.25,3.8500,NaN,75.500000,7.190000,NaN,365.4
4,"Flour, rice, glutinous",foundation_food,1500.00,1.1600,0.000,80.100000,6.690000,NaN,357.6
5,"Flour, pastry, unenriched, unbleached",foundation_food,1500.00,1.6400,0.000,77.200000,8.750000,NaN,358.6
6,"Onions, white, raw",foundation_food,35.00,0.1300,0.000,7.680000,0.890000,1.2000,35.4
7,"Apples, red delicious, with skin, raw",foundation_food,258.00,0.2100,0.000,14.800000,0.190000,2.0000,61.8
8,"Apples, honeycrisp, with skin, raw",foundation_food,60.00,0.1000,0.000,14.700000,0.100000,1.7000,60.1
9,"Apples, granny smith, with skin, raw",foundation_food,59.00,0.1400,0.000,14.200000,0.270000,2.5000,59.1
10,"Apples, gala, with skin, raw",foundation_food,61.00,0.1500,0.000,14.800000,0.130000,2.1000,61.1
11,"Apples, fuji, with skin, raw",foundation_food,65.00,0.1600,0.000,15.700000,0.150000,2.1000,64.8
12,"Flour, amaranth",foundation_food,NaN,6.2360,NaN,68.778700,13.209300,7.2090,384.1
13,"Flour, quinoa",foundation_food,NaN,6.6010,NaN,69.524650,11.922350,6.2950,385.2
14,"Flour, sorghum",foundation_food,NaN,3.5860,NaN,77.391230,8.272770,6.0190,374.9
15,"Flour, buckwheat",foundation_food,NaN,2.4840,0.000,75.018080,8.884920,10.3500,358.0
16,"Flour, rye",foundation_food,NaN,1.9080,0.000,77.161800,8.395200,13.6800,359.4
17,"Flour, barley",foundation_food,NaN,2.4500,0.000,77.398320,8.721680,12.7900,366.5
18,"Flour, cassava",foundation_food,NaN,0.4938,0.000,87.312975,0.918225,4.8340,357.4
19,"Buckwheat, whole grain",foundation_food,NaN,3.0390,NaN,71.130660,11.065340,4.0460,356.1
20,"Millet, whole grain",foundation_food,NaN,4.1940,NaN,74.446230,10.021770,2.6190,375.6
21,"Rice, brown, long grain, unenriched, raw",foundation_food,NaN,3.3060,NaN,76.687950,7.253050,3.0210,365.5
22,"Rice, white, long grain, unenriched, raw",foundation_food,NaN,1.0330,0.000,80.313150,7.038850,0.1488,358.7
23,"Beef, ground, 90% lean meat / 10% fat, raw",foundation_food,NaN,12.8500,5.051,0.000000,18.156250,NaN,188.3
24,"Beef, ground, 80% lean meat / 20% fat, raw",foundation_food,NaN,19.4400,6.845,0.000000,17.531250,NaN,245.1
25,"Pork, ground, raw",foundation_food,NaN,17.4900,6.283,0.000000,17.806250,NaN,228.6
26,"Chicken, ground, with additives, raw",foundation_food,NaN,7.1610,1.559,0.000000,17.912500,NaN,136.1
27,"Turkey, ground, 93% lean/ 7% fat, raw",foundation_food,NaN,9.5910,2.264,0.000000,17.343750,NaN,155.7
28,"Nuts, brazilnuts, raw",foundation_food,NaN,57.4300,NaN,21.642160,15.036840,5.9840,663.6
29,"Nuts, cashew nuts, raw",foundation_food,NaN,38.8600,NaN,36.288700,17.442300,4.1040,564.7
30,"Nuts, hazelnuts or filberts, raw",foundation_food,NaN,53.4900,NaN,26.501200,13.493800,8.4100,641.4
31,"Peanuts, raw",foundation_food,NaN,43.2800,NaN,26.498000,23.205000,8.0140,588.3
32,"Flour, chestnut",foundation_food,NaN,4.6360,0.689,80.450250,5.286750,8.7110,384.7
33,"Nuts, macadamia nuts, raw",foundation_food,NaN,64.9300,NaN,24.094300,7.785700,7.5630,711.9
34,"Nuts, pistachio nuts, raw",foundation_food,NaN,45.0200,NaN,27.694300,20.505700,6.9690,598.0
35,"Seeds, pumpkin seeds (pepitas), raw",foundation_food,NaN,40.0300,NaN,18.675100,29.907900,5.0790,554.6
36,"Seeds, sunflower seed, kernel, raw",foundation_food,NaN,48.4400,NaN,24.500700,18.873300,7.2150,609.5
37,"Flour, coconut",foundation_food,NaN,15.2800,13.999,58.902500,16.138500,34.2400,437.7
38,"Beans, cannellini, dry",foundation_food,NaN,2.1990,0.000,59.795500,21.562500,NaN,345.2
39,"Chickpeas, (garbanzo beans, bengal gram), dry",foundation_food,NaN,6.2740,NaN,60.358000,21.275000,NaN,383.0
40,"Lentils, dry",foundation_food,NaN,1.9250,0.000,62.171250,23.568750,NaN,360.3
41,"Blackeye pea, dry",foundation_food,NaN,2.4190,0.000,61.836000,21.225000,NaN,354.0
42,"Beans, black, canned, sodium added, drained an...",foundation_food,NaN,1.2730,0.000,19.813500,6.912500,NaN,118.4
43,"Beans, navy, canned, sodium added, drained and...",foundation_food,NaN,1.3980,0.000,19.983250,6.568750,NaN,118.8
44,"Beans, cannellini, canned, sodium added, drain...",foundation_food,NaN,1.1690,0.000,18.818500,7.412500,NaN,115.4
45,"Chickpeas (garbanzo beans, bengal gram), canne...",foundation_food,NaN,3.0960,NaN,20.320250,7.018750,NaN,137.2
46,"Beans, kidney, dark red, canned, sodium added,...",foundation_food,NaN,1.2560,0.000,21.030000,7.800000,NaN,126.6
47,"Beans, kidney, light red, canned, sodium added...",foundation_food,NaN,1.2990,0.000,21.446750,7.306250,NaN,126.7
48,"Peas, green, sweet, canned, sodium added, suga...",foundation_food,NaN,1.1530,0.000,12.707625,4.734375,NaN,80.1
49,"Beans, pinto, canned, sodium added, drained an...",foundation_food,NaN,1.2660,0.000,19.600250,6.693750,NaN,116.6

In [ ]:
# replace NaN in fibre column with 0 where likely 0
import numpy as np

df_clean["Fiber, total dietary"] = np.where(
    (df_clean["Carbohydrate, by difference"] < 5) &
    (df_clean["Fiber, total dietary"].isna()),
    0,
    df_clean["Fiber, total dietary"]
)

df_clean.head(50)

,food_item,data_type,Energy,Total lipid (fat),"Fatty acids, total saturated","Carbohydrate, by difference",Protein,"Fiber, total dietary",energy_kcal_calculated
0,"Garlic, raw",foundation_food,597.00,0.3800,0.000,28.200000,6.620000,2.7000,142.7
1,"Flour, soy, defatted",foundation_food,366.00,3.3300,NaN,32.900000,51.100000,NaN,366.0
2,"Flour, soy, full-fat",foundation_food,1890.00,20.7000,NaN,27.900000,38.600000,NaN,452.3
3,"Flour, rice, brown",foundation_food,365.25,3.8500,NaN,75.500000,7.190000,NaN,365.4
4,"Flour, rice, glutinous",foundation_food,1500.00,1.1600,0.000,80.100000,6.690000,NaN,357.6
5,"Flour, pastry, unenriched, unbleached",foundation_food,1500.00,1.6400,0.000,77.200000,8.750000,NaN,358.6
6,"Onions, white, raw",foundation_food,35.00,0.1300,0.000,7.680000,0.890000,1.2000,35.4
7,"Apples, red delicious, with skin, raw",foundation_food,258.00,0.2100,0.000,14.800000,0.190000,2.0000,61.8
8,"Apples, honeycrisp, with skin, raw",foundation_food,60.00,0.1000,0.000,14.700000,0.100000,1.7000,60.1
9,"Apples, granny smith, with skin, raw",foundation_food,59.00,0.1400,0.000,14.200000,0.270000,2.5000,59.1
10,"Apples, gala, with skin, raw",foundation_food,61.00,0.1500,0.000,14.800000,0.130000,2.1000,61.1
11,"Apples, fuji, with skin, raw",foundation_food,65.00,0.1600,0.000,15.700000,0.150000,2.1000,64.8
12,"Flour, amaranth",foundation_food,NaN,6.2360,NaN,68.778700,13.209300,7.2090,384.1
13,"Flour, quinoa",foundation_food,NaN,6.6010,NaN,69.524650,11.922350,6.2950,385.2
14,"Flour, sorghum",foundation_food,NaN,3.5860,NaN,77.391230,8.272770,6.0190,374.9
15,"Flour, buckwheat",foundation_food,NaN,2.4840,0.000,75.018080,8.884920,10.3500,358.0
16,"Flour, rye",foundation_food,NaN,1.9080,0.000,77.161800,8.395200,13.6800,359.4
17,"Flour, barley",foundation_food,NaN,2.4500,0.000,77.398320,8.721680,12.7900,366.5
18,"Flour, cassava",foundation_food,NaN,0.4938,0.000,87.312975,0.918225,4.8340,357.4
19,"Buckwheat, whole grain",foundation_food,NaN,3.0390,NaN,71.130660,11.065340,4.0460,356.1
20,"Millet, whole grain",foundation_food,NaN,4.1940,NaN,74.446230,10.021770,2.6190,375.6
21,"Rice, brown, long grain, unenriched, raw",foundation_food,NaN,3.3060,NaN,76.687950,7.253050,3.0210,365.5
22,"Rice, white, long grain, unenriched, raw",foundation_food,NaN,1.0330,0.000,80.313150,7.038850,0.1488,358.7
23,"Beef, ground, 90% lean meat / 10% fat, raw",foundation_food,NaN,12.8500,5.051,0.000000,18.156250,0.0000,188.3
24,"Beef, ground, 80% lean meat / 20% fat, raw",foundation_food,NaN,19.4400,6.845,0.000000,17.531250,0.0000,245.1
25,"Pork, ground, raw",foundation_food,NaN,17.4900,6.283,0.000000,17.806250,0.0000,228.6
26,"Chicken, ground, with additives, raw",foundation_food,NaN,7.1610,1.559,0.000000,17.912500,0.0000,136.1
27,"Turkey, ground, 93% lean/ 7% fat, raw",foundation_food,NaN,9.5910,2.264,0.000000,17.343750,0.0000,155.7
28,"Nuts, brazilnuts, raw",foundation_food,NaN,57.4300,NaN,21.642160,15.036840,5.9840,663.6
29,"Nuts, cashew nuts, raw",foundation_food,NaN,38.8600,NaN,36.288700,17.442300,4.1040,564.7
30,"Nuts, hazelnuts or filberts, raw",foundation_food,NaN,53.4900,NaN,26.501200,13.493800,8.4100,641.4
31,"Peanuts, raw",foundation_food,NaN,43.2800,NaN,26.498000,23.205000,8.0140,588.3
32,"Flour, chestnut",foundation_food,NaN,4.6360,0.689,80.450250,5.286750,8.7110,384.7
33,"Nuts, macadamia nuts, raw",foundation_food,NaN,64.9300,NaN,24.094300,7.785700,7.5630,711.9
34,"Nuts, pistachio nuts, raw",foundation_food,NaN,45.0200,NaN,27.694300,20.505700,6.9690,598.0
35,"Seeds, pumpkin seeds (pepitas), raw",foundation_food,NaN,40.0300,NaN,18.675100,29.907900,5.0790,554.6
36,"Seeds, sunflower seed, kernel, raw",foundation_food,NaN,48.4400,NaN,24.500700,18.873300,7.2150,609.5
37,"Flour, coconut",foundation_food,NaN,15.2800,13.999,58.902500,16.138500,34.2400,437.7
38,"Beans, cannellini, dry",foundation_food,NaN,2.1990,0.000,59.795500,21.562500,NaN,345.2
39,"Chickpeas, (garbanzo beans, bengal gram), dry",foundation_food,NaN,6.2740,NaN,60.358000,21.275000,NaN,383.0
40,"Lentils, dry",foundation_food,NaN,1.9250,0.000,62.171250,23.568750,NaN,360.3
41,"Blackeye pea, dry",foundation_food,NaN,2.4190,0.000,61.836000,21.225000,NaN,354.0
42,"Beans, black, canned, sodium added, drained an...",foundation_food,NaN,1.2730,0.000,19.813500,6.912500,NaN,118.4
43,"Beans, navy, canned, sodium added, drained and...",foundation_food,NaN,1.3980,0.000,19.983250,6.568750,NaN,118.8
44,"Beans, cannellini, canned, sodium added, drain...",foundation_food,NaN,1.1690,0.000,18.818500,7.412500,NaN,115.4
45,"Chickpeas (garbanzo beans, bengal gram), canne...",foundation_food,NaN,3.0960,NaN,20.320250,7.018750,NaN,137.2
46,"Beans, kidney, dark red, canned, sodium added,...",foundation_food,NaN,1.2560,0.000,21.030000,7.800000,NaN,126.6
47,"Beans, kidney, light red, canned, sodium added...",foundation_food,NaN,1.2990,0.000,21.446750,7.306250,NaN,126.7
48,"Peas, green, sweet, canned, sodium added, suga...",foundation_food,NaN,1.1530,0.000,12.707625,4.734375,NaN,80.1
49,"Beans, pinto, canned, sodium added, drained an...",foundation_food,NaN,1.2660,0.000,19.600250,6.693750,NaN,116.6

In [ ]:
# the following columns are mandatory for modelling, in case they are NaN they are dropped
# CAVE: there will reamain NaN in fibre and saturated fats!
cols_required = [
    "food_item",
    "energy_kcal_calculated",
    "Total lipid (fat)",
    "Carbohydrate, by difference",
    "Protein",
    "Fiber, total dietary",
    "Fatty acids, total saturated"
]

df_clean = df_clean.dropna(subset=cols_required)

In [10]:
# df_clean.head(50)

len(df_clean)

7521

In [63]:
import sys
import os

# Add parent folder to Python path
sys.path.append(os.path.abspath(".."))

In [ ]:
from nutrimap_app.category_mapping import assign_food_group
df_clean["food_category"] = df_clean.apply(assign_food_group, axis=1)
df_clean.head(50)